// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8yt7AcZX-HOw4nAaJ9QB7dNTgnHZtYk',
    appId: '1:888058212243:web:72d6ba30da878787658266',
    messagingSenderId: '888058212243',
    projectId: 'doadores-app',
    authDomain: 'doadores-app.firebaseapp.com',
    storageBucket: 'doadores-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI2_AVuLoY23kIe1cWgkGIjFJ-3TSumrI',
    appId: '1:888058212243:android:f05be783157d6871658266',
    messagingSenderId: '888058212243',
    projectId: 'doadores-app',
    storageBucket: 'doadores-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCRdLm8ax2N_Q2sou9u7PdaFuhMRboWug',
    appId: '1:888058212243:ios:7241baed6d00c7d0658266',
    messagingSenderId: '888058212243',
    projectId: 'doadores-app',
    storageBucket: 'doadores-app.firebasestorage.app',
    iosBundleId: 'com.example.projectoAplpFinal',
  );
}
